[project]
name = "dsubot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "disnake>=2.10.1",
    "pydantic-settings>=2.8.1",
    "rich>=13.9.4",
]
